10 api for student management
presentium/api pull request #11
Opened 2024-08-22 20:53 UTC by massteff

### Description

This PR aims to add the necessary API for student management.

### Linked Issues

[This issue](https://github.com/orgs/presentium/projects/1/views/1?pane=issue&itemId=70728925)

2024-08-25 16:54 UTC, Lutonite requested changes

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +    @Autowired
Tu peux juste utiliser `@RequiredArgsConstructor` de lombok au niveau de la classe, pas besoin de mettre `@Autowired` sur les constructeurs

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +@RequestMapping("/v1/student")
ce serait bien d'annoter avec `@Tag` comme les autres controlleurs, pour que la doc swagger soit plus lisible

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +@RequestMapping("/v1/student")
Une api REST spécifie une resource selon son nom au pluriel et on va explicitement annoncer qu'on produit du JSON, ça devrait être `@RequestMapping(path = "/v1/students", produces = MediaType.APPLICATION_JSON_VALUE)`

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +    @Transactional(readOnly = true)
En général je rajoute aussi `rollbackFor = Throwable.class` sinon des fois ça rollback pas en cas de checked exception, même si techniquement on en aura pas ici

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +    @GetMapping("/all")
en API REST l'endpoint qui retourne une liste de resource devrait être sur le chemin de la resource. Donc pour la liste des étudiants ça devrait être `/v1/students`. Du coup il faut juste mettre `@GetMapping` ici.

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +    @PostMapping("/add")
en API REST pour créer une resource on fait un POST sur la collection de resources, donc ça devrait être POST `/v1/students` pour créer un student. il suffit de changer en `@PostMapping`

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/StudentController.java
> +    public void addStudent(@RequestBody StudentRequest studentBody) {
```suggestion
    public void addStudent(@RequestBody @Valid StudentRequest studentBody) {
```

sinon tes annotations de validation seront pas vérifiées

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/api/student/request/StudentRequest.java
> +    @NotNull private final String firstName;
```suggestion
    private final @NotBlank String firstName;
```

pareil pour les autres strings, ça évitera des strings vide ou avec que des espaces

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/business/service/StudentService.java
> +        Student student = new Student();
ça aurait été plus simple de faire le mapping avec mapstruct, pour t'éviter de devoir le faire depuis le service, donc le controller utilise le mapper pour convertir en User et soit tu appelles le service avec le modèle DB converti soit tu fais directement le save depuis le controller.

en général quand un service est aussi simple je m'embête pas à le faire avec un service et je fais tout dans le controlleur

2024-08-25 16:54 UTC, Lutonite commented on src/main/java/ch/presentium/backend/business/service/StudentService.java
> +        return studentRepository.findById(id).orElse(null);
on va préférer lancer une exception pour générer un 404 que de retourner null qui ne va pas être correctement affiché à l'API, je pense que le mieux est de retourner l'optional ici et d'ajouter un orElseThrow dans le controlleur

2024-08-26 13:35 UTC, massteff commented
Making tests

2024-08-31 15:02 UTC, Lutonite approved these changes

2024-08-31 15:02 UTC, merged